; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Apr 07 2019 16:17:17 GMT+0200 (Central European Summer Time)

