; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Sun Apr 07 2019 16:17:17 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

